apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
home: https://helm.sh/helm
maintainers:
  - email: email@example.com
    name: Vladimir Semashkin
name: grpc-python-server
sources:
  - https://github.com/helm/helm
version: 1.0.0